
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import{Header} from "./_components/header";
import Footer from "./_components/footer";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {/* <Header /> */}
    <>
        <Header />
        {children}
        <Footer />
     
     </>
    
  );
}
