import { Header } from "./_components/header";
import Footer from "./_components/footer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`} suppressHydrationWarning>
        <>
          <Header />
          {children}
          <Footer />
        </>
      </body>
    </html>
  );
}
