import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
// import "./global";
import { Toaster } from "sonner";

const plusSansJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusSansJakarta.className} antialiased`}>
        <Toaster
          position="bottom-center"
          closeButton
          duration={3000}
          expand={true}
          richColors
          theme="dark"
        />
        {children}
      </body>
    </html>
  );
}
